name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [ '5.x' ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: versx/chuckdevicecontroller/master
          tag_with_ref: true
